#### egui-components/Cargo.toml
[package]
name = "egui-components"
version = "0.1.0"
edition = "2021"

[dependencies]
# Use a direct reference to eframe with version instead of workspace
eframe = "0.24.1"
env_logger = "0.11.8"

